name: 'aaropa_builder_package'
description: |
  Build a DEB package and produce artifact for the current project
inputs:
  distro:
    description: |
      The Debian-based Linux distribution to build the package for
      Used in Dockerfile
    required: true
    default: "debian:latest"
  arch:
    description: |
      The architecture(s) to build the package for
    required: true
    default: "amd64"
  docker_arch_specific:
    description: |
      Force docker to use arch-specific container images
    required: true
    default: false
  build_arguments:
    description: |
      Arguments to pass to the command dpkg-buildpackage
    required: true
    default: "-b"
  build_options:
    description: |
      Options to pass to the build process (via DEB_BUILD_OPTIONS)
    required: true
    default: ""
  build_profiles:
    description: |
      Options to pass to the build process (via DEB_BUILD_PROFILES)
    required: true
    default: ""
  gpg_signing_key:
    description: |
      The GPG key to use for signing the package
    required: false
  package_name:
    description: |
      Overrides the name of the package to build
    required: false
  package_version:
    description: |
      Overrides the version of the package to build
    required: false
  package_maintainer:
    description: |
      Overrides the maintainer of the package maintainer
      The syntax is Maintainer Name <maintainer@email>
      Maintainer must match the owner of gpg_signing_key (if specified)
    required: false
  package_class:
    description: |
      Set the package class
      Available classes are (s) single, (i) arch-independent, (l) library, (p) python
    required: true
    default: "s"
  package_generate_orig:
    description: |
      Generate the .orig source package
    required: false
    default: false
outputs:
  artifact_path:
    description: |
      The path to the generated DEB packages, build infomation and metadata file
    value: "built-deb-files.zip"
runs:
  using: "composite"
  steps:
    - name: Set Dockerfile distro
      run: |
        sed -i -r 's|^FROM .+$|FROM ${{ inputs.distro }}|gi' ${{ github.action_path }}/Dockerfile
      shell: bash

    - name: Setup maintainer info
      if: ${{ inputs.package_maintainer != '' }}
      env:
        DEB_MAINTAINER: ${{ inputs.package_maintainer }}
      run: |
        echo "DEBEMAIL='$(echo $DEB_MAINTAINER | awk -F '<' '{print $2}' | awk -F '>' '{print $1}')'" >>.env
        echo "DEBFULLNAME='$(echo $DEB_MAINTAINER | awk -F '<' '{print $1}')'" >>.env
      shell: bash

    - name: Generate debian package info
      if: ${{ inputs.package_name != '' && inputs.package_version != '' }}
      env:
        DEB_GENERATE_ORIG: ${{ inputs.package_generate_orig }}
      run: |
        apt install -y debhelper
        
        if [ "$DEB_GENERATE_ORIG" == true ]; then
          ARG_GEN_ORIG=-n
        fi

        source .env

        dh_make -y -d \
          -p ${{ inputs.package_name }}_${{ inputs.package_version }} \
          -C ${{ inputs.package_class }} \
          ${DEBEMAIL:+ -e $DEBEMAIL} \
          $ARG_GEN_ORIG
      shell: bash

    - name: Set up environment
      run: |
        echo "DEB_ARCH='${{ inputs.arch }}'" >>.env
        echo "DEB_BUILD_ARGS='${{ inputs.build_arguments }}'" >>.env
        echo "DEB_BUILD_OPTIONS='${{ inputs.build_options }}'" >>.env
        echo "DEB_BUILD_PROFILES='${{ inputs.build_profiles }}'" >>.env
        echo "GPG_SECRET='${{ inputs.gpg_signing_key }}'" >>.env
        cat .env
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build packages using Docker
      run: |
        cp ${{ github.action_path }}/action_build.sh .
        for ARCH in ${{ inputs.arch }}; do
          dpkg-architecture -A $ARCH > .build_env

          docker buildx create --use --name debian-deb-$ARCH --buildkitd-flags '--allow-insecure-entitlement security.insecure'
          
          if [ '${{ inputs.docker_arch_specific }}' = true ]; then
            PLATFORM=$ARCH
          else
            PLATFORM=$(dpkg --print-architecture)
          fi

          case "$PLATFORM" in
          i386) PLATFORM=386 ;;
          arm64) PLATFORM=arm64/v8 ;;
          *) ;;
          esac

          # Build image
          mkdir -p build-$ARCH
          docker buildx build --builder debian-deb-$ARCH --platform linux/$PLATFORM -f ${{ github.action_path }}/Dockerfile -t debian-$ARCH --allow security.insecure --output type=local,dest=build-$ARCH --rm .

          # Export
          bash -c "cp build-$ARCH/*.{deb,udeb,buildinfo,changes} . | :"
          sudo rm -rf build-$ARCH
        done
      shell: bash

    - name: Generate metadata.yml
      env:
        DEB_ARCH: ${{ inputs.arch }}
      run: |
        ${{ github.action_path }}/action_gen-metadata.sh
      shell: bash

    - name: Compress build files
      run: zip -j 'built-deb-files.zip' *.deb *.udeb *.buildinfo *.changes metadata.yml
      shell: bash

    - name: Clean up
      run: sudo rm -rf build build.tar
      shell: bash
